name: build-test

on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        include:
        - name: OpenMP-On
          os: macos-latest
          path: ~/Library/Caches/pip
          python-version: 3.9
        - name: OpenMP-OFF
          os: macos-latest
          path: ~/Library/Caches/pip
          python-version: 3.9

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version : ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }} cache 
      run: which python > ~/.python3_path.txt
    - uses: actions/cache@v2
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('~/.python3_path.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-
    - name: Install dependencies 
      run: |
        pip install --upgrade pip wheel setuptools build
        pip install -r requirements.txt
    - name: Install Eigen3 on ${{ matrix.os }}
      run: brew install eigen
    - name: Install OpenMP on ${{ matrix.os }}
      if: ${{ matrix.name == 'OpenMP-On'}}
      run: brew install libomp 
    - name: Test 
      shell: bash
      run: |
        export USE_TEST=1
        python setup.py build --debug test
